""""add_missing_user_columns"

Revision ID: f85fd87cabea
Revises: 498dc86bc42b
Create Date: 2024-12-26 16:48:50.829576

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f85fd87cabea"
down_revision: Union[str, None] = "498dc86bc42b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=False))
    op.add_column(
        "users",
        sa.Column("is_superuser", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column("users", sa.Column("last_login", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "last_login")
    op.drop_column("users", "is_superuser")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
