"""initial

Revision ID: 2b17fc00376c
Revises: 
Create Date: 2024-12-29 16:32:19.381255+00:00

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2b17fc00376c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "failed_login_attempts",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("last_failed_login", sa.DateTime(), nullable=True),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
        schema="backtest",
    )
    op.create_index(
        "ix_users_email", "users", ["email"], unique=True, schema="backtest"
    )
    op.create_index(
        "ix_users_username", "users", ["username"], unique=True, schema="backtest"
    )

    op.create_table(
        "strategies",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="backtest",
    )

    op.create_table(
        "backtests",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("strategy_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("parameters", postgresql.JSONB(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["strategy_id"], ["backtest.strategies.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="backtest",
    )
    op.create_index(
        "ix_backtests_id", "backtests", ["id"], unique=True, schema="backtest"
    )
    op.create_index(
        "ix_backtests_name", "backtests", ["name"], unique=True, schema="backtest"
    )

    op.create_table(
        "backtest_results",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("backtest_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("position_value", sa.Float(), nullable=False),
        sa.Column("portfolio_value", sa.Float(), nullable=False),
        sa.Column("signal_data", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["backtest_id"], ["backtest.backtests.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="backtest",
    )
    op.create_index(
        "ix_backtest_results_id",
        "backtest_results",
        ["id"],
        unique=True,
        schema="backtest",
    )

    op.create_table(
        "metrics",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("backtest_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["backtest_id"], ["backtest.backtests.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="backtest",
    )
    op.create_index("ix_metrics_id", "metrics", ["id"], unique=True, schema="backtest")

    op.create_table(
        "audit_logs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("method", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("request_body", postgresql.JSONB(), nullable=True),
        sa.Column("error_detail", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["backtest.users.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="backtest",
    )
    op.create_index(
        "ix_audit_logs_id", "audit_logs", ["id"], unique=True, schema="backtest"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_logs_id", table_name="audit_logs", schema="backtest")
    op.drop_table("audit_logs", schema="backtest")
    op.drop_index("ix_metrics_id", table_name="metrics", schema="backtest")
    op.drop_table("metrics", schema="backtest")
    op.drop_index(
        "ix_backtest_results_id", table_name="backtest_results", schema="backtest"
    )
    op.drop_table("backtest_results", schema="backtest")
    op.drop_index("ix_backtests_id", table_name="backtests", schema="backtest")
    op.drop_index("ix_backtests_name", table_name="backtests", schema="backtest")
    op.drop_table("backtests", schema="backtest")
    op.drop_table("strategies", schema="backtest")
    op.drop_index("ix_users_email", table_name="users", schema="backtest")
    op.drop_index("ix_users_username", table_name="users", schema="backtest")
    op.drop_table("users", schema="backtest")
    # ### end Alembic commands ###
